-- ============================================
-- V10__migrate_encrypted_fields.sql - 敏感字段加密迁移占位 (P4.1)
-- ============================================
-- 本迁移文件为占位,实际的明文→密文迁移由 DataMigrationService.migrateToEncrypted()
-- 在应用层完成。原因:
--   1. AES-GCM 加密需要应用层密钥,SQL 层无法访问;
--   2. 加密在 TypeHandler 层自动完成,新写入的数据会自动加密;
--   3. 历史明文数据需通过迁移工具一次性读取→加密→更新。
--
-- 迁移流程(管理员手动执行):
--   1. 配置环境变量 CRYPTO_SECRET_KEY(32 字节 base64 密钥)
--   2. 启动应用(TypeHandler 自动对新数据加密)
--   3. 调用 POST /api/system/data-migration/migrate-encrypted 触发历史数据迁移
--      (接口需 ADMIN 权限,详见 DataMigrationController)
--   4